export const prettyLabels = {
    "kpd": "Kills per Death ratio",
    "eliminations": "Eliminations",
    "final_blows": "Final blows",
    "deaths": "Deaths",
    "overwatchguid0x08600000000003e9": "Overwatch guid 3e9",
    "overwatchguid0x086000000000052a": "Overwatch guid 52a",
    "solo_kills": "Solo kills",
    "medals_silver": "Silver medals",
    "games_won": "Games won",
    "healing_done_most_in_game": "Most healing done in game",
    "healing_done": "Healing done",
    "eliminations_most_in_game": "Most eliminations in game",
    "objective_kills": "Objective kills",
    "defensive_assists_most_in_game": "Most defensive assists in game",
    "melee_final_blow_most_in_game": "Melee final blows",
    "environmental_deaths": "Environmental deaths",
    "final_blows_most_in_game": "Most final blows in game",
    "medals_gold": "Gold medals",
    "objective_time": "Objective time",
    "cards": "Cards",
    "medals": "Medals",
    "time_spent_on_fire_most_in_game": "Most time spent on fire",
    "all_damage_done": "All damage done",
    "defensive_assists": "Defensive assists",
    "time_played": "Time played (hours)",
    "objective_kills_most_in_game": "Most objective kills in game",
    "medals_bronze": "Bronze medals",
    "objective_time_most_in_game": "Most time on objective",
    "melee_final_blows": "Melee final blows",
    "solo_kills_most_in_game": "Most solo kills in game",
    "all_damage_done_most_in_game": "Most damage done in game",
    "environmental_kills": "Environmental kills",
    "multikills": "Multikills",
    "multikill_best": "Most multikills in game",
    "time_spent_on_fire": "Time spent on fire",
    "turrets_destroyed": "Turrets destroyed",
    "environmental_kill_most_in_game":"Most enviornmental kills in game",
    "kill_streak_best": "Best kill streak",
    "barrier_damage_done": "Barrier damage done",
    "melee_final_blow":"Melee final blow",
    "offensive_assists_most_in_game":"Most offensive assists in game",
    "turrets_destroyed_most_in_game":"Most turrets destroyer in game",
    "hero_damage_done": "Hero damage done",
    "offensive_assists": "Offensive assists",
    "hero_damage_done_most_in_game": "Most damage done in game",
    "ana":"Ana",
    "junkrat":"Junkrat",
    "sombra":"Sombra",
    "dva":"Dva",
    "genji":"Genji",
    "reaper":"Reaper",
    "reinhardt":"Reinhardt",
    "pharah":"Pharah",
    "orisa":"Orisa",
    "lucio":"Lucio",
    "zarya":"Zarya",
    "mercy":"Mercy",
    "bastion":"Bastion",
    "zenyatta":"Zenyatta",
    "hanzo":"Hanzo",
    "roadhog":"Roadhog",
    "winston":"Winston",
    "soldier76":"Soldier76",
    "mei":"Mei",
    "symmetra":"Symmetra",
    "mccree":"McCree",
    "torbjorn":"Torbjorn",
    "tracer":"Tracer",
    "widowmaker":"Widowmaker",
    "doomfist":"Doomfirst",
    "unscoped_accuracy":"Unscoped accuracy",
    "nano_boosts_applied":"Nano boosts applied",
    "nano_boost_assists_most_in_game":"Most nano boosts in game",
    "scoped_accuracy_best_in_game":"Best scoped accuracy in game",
    "nano_boost_assists":"Nano boost assists",
    "scoped_accuracy":"Scoped accuracy",
    "enemies_slept_most_in_game":"Most enemies slept in game",
    "rip_tire_kills_most_in_game":"Most rip tire kills in game",
    "rip_tire_kills": "Rip tire kills",
    "enemies_trapped_most_in_game":"Most enemies trapped in game",
    "enemies_trapped":"Enemies trapped",
    "mech_deaths":"Mech deaths",
    "damage_blocked":"Damage blocked",
    "damage_blocked_most_in_game":"Most damage blocked in game",
    "mechs_called_most_in_game":"Most mechs called in game",
    "mechs_called":"Mechs called",
    "dragonblade_kills_most_in_game":" Most dragonblade kills in game",
    "damage_reflected_most_in_game":"Most damage reflected in game",
    "dragonblade_kills":"Dragonblade kills",
    "damage_reflected": "Damage reflected",
    "dragonblades": "Dragonblades",
    "death_blossom_kills_most_in_game": "Most death blossom kills in game",
    "death_blossom_kills":"Death blossom kills",
    "fire_strike_kills":"Fire strike kills",
    "fire_strike_kills_most_in_game":"Most fire strike kills in game",
    "charge_kills_most_in_game":"Most charge kills in game",
    "earthshatter_kills_most_in_game":"Most earthshatter kills in game",
    "earthshatter_kills":"Earthshatter kills",
    "charge_kills": "Charge kills",
    "rocket_direct_hits_most_in_game":"Most rocket direct hits in game",
    "barrage_kills_most_in_game":"Most barrage kills in game",
    "rocket_direct_hits":"Rocket direct hits",
    "barrage_kills":"Barrage kills",
    "sound_barriers_provided":"Sound barriers porvided",
    "sound_barriers_provided_most_in_game":"Most sound barriers provided in game",
    "projected_barriers_applied":"Projected barriers applied",
    "graviton_surge_kills_most_in_game":"Most graviton surge kills in game",
    "high_energy_kills_most_in_game":"Most high energy kills in game",
    "high_energy_kills":"High energy kills",
    "graviton_surge_kills":"Graviton surge kills",
    "energy_maximum":"Energy maximum",
    "lifetime_energy_accumulation":"Lifetime energy accumulation",
    "players_resurrected_most_in_game":"Most players ressurected in game",
    "players_resurrected":"Players resurrected",
    "recon_kill_most_in_game":"Recon kills most in game",
    "recon_kills":"Recon kills",
    "tank_kills_most_in_game":"Most tank kills in game",
    "sentry_kills_most_in_game":"Most sentry kills in game",
    "sentry_kills":"Sentry kills",
    "tank_kills":"Tank kills",
    "transcendence_healing_best":"Transcendence healing best",
    "scatter_arrow_kills":"Scatter arrow kills",
    "dragonstrike_kills":"Dragonstrike kills",
    "recon_assists_most_in_game":"Most recon assists in game",
    "dragonstrike_kills_most_in_game":"Most dragonstrike kills in game",
    "scatter_arrow_kills_most_in_game":"Most scatter arrow kills in game",
    "hook_accuracy":"Hook accuracy",
    "enemies_hooked":"Enemies hooked",
    "whole_hog_kills":"Whole hog kills",
    "hooks_attempted": "Hooks attempted",
    "whole_hog_kills_most_in_game":"Most whole hog kills in game",
    "enemies_hooked_most_in_game":"Most enemies hooked in game",
    "hook_accuracy_best_in_game":"Best hook accuracy in game",
    "players_knocked_back":"Players knocked back",
    "players_knocked_back_most_in_game":"Most players knocked back in game",
    "jump_pack_kills":"Jump pack kills",
    "jump_pack_kills_most_in_game":"Most jump pack kills in game",
    "biotic_field_healing_done":"Biotic field healing done",
    "helix_rockets_kills":"Helix rocket kills",
    "helix_rockets_kills_most_in_game":"Most helix rocket kills in game",
    "tactical_visor_kills":"Tactical visor kills",
    "tactical_visor_kills_most_in_game":"Most tactical visor kills in game",
    "biotic_fields_deployed":"Biotic fields deployed",
    "enemies_frozen":"Enemies frozen",
    "enemies_frozen_most_in_game":"Most enemies frozen in game",
    "blizzard_kills":"Blizzard kills",
    "blizzard_kills_most_in_game":"Most blizzard kills in game",
    "sentry_turret_kills":"Sentry turret kills",
    "players_teleported":"Players teleported",
    "players_teleported_most_in_game":"Most players teleported in game",
    "sentry_turret_kills_most_in_game":"Most sentry turret kills in game",
    "teleporter_uptime_best_in_game":"Best teleported uptime in game",
    "teleporter_uptime":"Teleported uptime",
    "deadeye_kills":"Deadeye kills",
    "fan_the_hammer_kills":"Fan the hammer kills",
    "deadeye_kills_most_in_game":"Most deadeye kills in game",
    "torbjorn_kills_most_in_game":"Most torbjorn kills in game",
    "molten_core_kills_most_in_game":"Most molten core kills in game",
    "molten_core_kills":"Molten core kills",
    "armor_packs_created":"Armor packs created",
    "torbjorn_kills":"Torbjorn kills",
    "turret_kills":"Turret kills",
    "pulse_bomb_kills":"Pulse bomb kills",
    "pulse_bombs_attached":"Pulse bombs attached",
    "pulse_bomb_kills_most_in_game":"Most pulse bomb kills in game",
    "pulse_bombs_attached_most_in_game":"Most pulse bombs attached in game",
    "venom_mine_kills_most_in_game":"Most venom mine kills in game",
    "scoped_critical_hits":"Scoped critical hits",
    "venom_mine_kills":"Venom mine kills",
    "scoped_critical_hits_most_in_game":"Most scoped critial hits in game",
    "eliminations_per_life":"Eliminations per life",
}